"""hh_id unique=False

Revision ID: fab1f010c082
Revises: 5b24b931be2d
Create Date: 2024-07-05 10:24:30.256228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab1f010c082'
down_revision: Union[str, None] = '5b24b931be2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vacancies_hh_id_key', 'vacancies', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('vacancies_hh_id_key', 'vacancies', ['hh_id'])
    # ### end Alembic commands ###
